version: "3"
services:
  # rabbitmq:
  #   image: rabbitmq:3
  #   environment:
  #   - RABBITMQ_DEFAULT_USER=guest
  #   - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - "127.0.0.1:5672:5672"
  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    container_name: flask
    ports:
      - 5000:5000
      
  react:
    build:
      context: .
      dockerfile: react.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true
  
